zaplatynska js
AndreiBakhtinov/team312 pull request #36
Opened 2023-11-13 11:19 UTC by zaplatynska-kira

2023-11-13 11:21 UTC, mavr1ke requested changes
приветствие должно быть выведено в консоль с помощью js

2023-11-13 11:22 UTC, alexlead requested changes
Folder name required (Требуется папка с названием пользователя)
Branch name (Название ветки)

2023-11-13 11:59 UTC, mavr1ke requested changes
файлы должны находится в каталоге с твоим именем

2023-11-13 17:14 UTC, alexlead approved these changes

2023-11-14 21:09 UTC, Tetiana-Ilienko approved these changes
Комментирую работу коллеги. Все отлично!

2023-11-16 02:21 UTC, JannTs approved these changes

2023-11-16 08:49 UTC, closed without merging